name: CI/CD Deployment to EC2

on:
  pull_request:
    branches: DeploymentStage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 (Adjusted Paths)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Navigate to your repository's location
            cd ~/GameSpace
            git pull origin main

            echo "Deploying Flask Backend using Gunicorn..."
            cd GameSpaceBackend
            # Activate the virtual environment if used:
            # source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn

            echo "Deploying React Frontend..."
            cd ../frontend
            npm install
            npm run build
            sudo systemctl daemon-reload
            sudo systemctl reload nginx

            echo "Deployment Complete!"
