name: CI/CD Deployment to EC2

on:
  pull_request:
    branches: DeploymentStage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          echo "Frontend build complete!"

      - name: List Build Artifacts
        run: ls -al frontend/dist

      # Clean remote target directory
      - name: Clean Remote Frontend Build Directory
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo rm -rf ~/GameSpace/frontend/build
            mkdir -p ~/GameSpace/frontend/build
            sudo chown $(whoami):$(whoami) ~/GameSpace/frontend/build

      # Transfer the built frontend files  
      - name: Deploy Frontend Build to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "frontend/dist"
          target: "~/GameSpace/frontend/build/"
          overwrite: true
          strip_components: '1'

      # Deploy backend and restart services on EC2
      - name: Deploy Backend and Restart Services on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/GameSpace
            git fetch origin main
            git reset --hard origin/main

            echo "Deploying Flask Backend using Gunicorn..."
            cd GameSpaceBackend
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install --break-system-packages -r requirements.txt
            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn

            echo "Adjusting file permissions on static files..."
            sudo chmod -R 755 ~/GameSpace/frontend/build
            sudo chown -R www-data:www-data ~/GameSpace/frontend/build

            echo "Reloading Nginx..."
            sudo systemctl daemon-reload
            sudo systemctl reload nginx

            echo "Deployment Complete!"

      # Restore .env files using GitHub Secrets
      - name: Restore Backend .env File
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Write the backend environment file
            echo "${{ secrets.BACKEND_ENV_FILE }}" > ~/GameSpace/GameSpaceBackend/.env
            # Set appropriate permissions (adjust as needed)
            chmod 600 ~/GameSpace/GameSpaceBackend/.env

      - name: Restore Frontend .env File
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Write the frontend environment file (if needed at runtime)
            echo "${{ secrets.FRONTEND_ENV_FILE }}" > ~/GameSpace/frontend/.env
            chmod 600 ~/GameSpace/frontend/.env
