name: CI/CD Deployment to EC2

on:
  pull_request:
    branches: DeploymentStage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the entire repository from GitHub
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Deploy both the backend and frontend to EC2
      - name: Deploy to EC2 (Monorepo)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Navigate to the root of your monorepo and pull the latest changes.
            cd /GameSpace
            git pull origin main

            # Deploying the Flask Backend
            echo "Deploying Flask Backend using Gunicorn..."
            cd GameSpaceBackend
            pip install -r requirements.txt
            # If you use a Python virtual environment, activate it here:
            # source venv/bin/activate
            sudo systemctl restart gunicorn

            # Deploying the React Frontend
            echo "Deploying React Frontend..."
            cd ../frontend
            npm install
            npm run build
            sudo systemctl reload nginx

            echo "Deployment Complete!"
